spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: ems #微服务名称
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?characterEncoding=UTF-8
    username: root
    password: 123456

server:
  servlet:
    context-path: /ems
    jsp:
      init-parameters:
        development: true #开启jsp页面热部署
mybatis:
  mapper-locations:  classpath:com/baizhi/ems/mapper/*.xml     #mapper配置文件的位置
  type-aliases-package: com.baizhi.ems.entity